# Generated by Django 4.1.5 on 2023-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_assignment_students_alter_course_assignments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='feedback',
        ),
        migrations.AddField(
            model_name='assignment',
            name='feedback',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
