# Generated by Django 4.1.5 on 2023-01-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_course_feedback_assignment_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='students',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assignments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
        ),
    ]
