# Generated by Django 4.1.5 on 2023-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_assignment_course_alter_assignment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
