# Generated by Django 4.1.5 on 2023-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
