# Generated by Django 4.1.5 on 2023-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_assignment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
