# Generated by Django 4.1.5 on 2023-02-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_students', to='backend.course')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_courses', to='backend.student')),
            ],
        ),
    ]
