# Generated by Django 4.1.5 on 2023-02-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='created_at',
        ),
    ]
